"""
utils/report_generator.py
--------------------------
Generates a human-readable Markdown report summarizing 
the data collection and processing execution.
"""

from pathlib import Path
from datetime import datetime
from colorama import Fore, init

init(autoreset=True)

# Directories
BASE_DIR = Path(__file__).resolve().parent.parent.parent
REPORTS_DIR = BASE_DIR / "data" / "reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)


def generate_markdown_report(user_email: str, results: dict) -> Path:
    """
    Creates a detailed execution report in Markdown format.
    
    Args:
        user_email: The account being processed.
        results: Dictionary containing summaries from all 9 steps.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    file_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_email = user_email.replace("@", "_at_").replace(".", "_")
    
    report_path = REPORTS_DIR / f"report_{safe_email}_{file_timestamp}.md"
    
    # Extract data safely with defaults
    cal = results.get('calendar', {})
    gmail = results.get('gmail', {})
    filter_res = results.get('filter', {})
    cat = results.get('categorization', {})
    link = results.get('linking', {})

    md_content = f"""# AI-Powered Personal Analytics - Execution Report
**Date:** {timestamp}
**Account:** {user_email}

---

## 📥 Layer 1: Data Integration (Collection)
Successfully extracted one year of data from Google APIs.

### 📅 Google Calendar
- **Total Events Fetched:** {cal.get('total_events', 0)}
- **Calendars Scanned:** {len(cal.get('calendars', []))}
- **Raw File:** `{cal.get('events_file', 'N/A')}`

### 📧 Gmail
- **Total Messages Fetched:** {gmail.get('total_messages', 0)}
- **Threads Identified:** {gmail.get('unique_threads', 0)}
- **Sent Items:** {gmail.get('sent_messages', 0)}
- **Raw File:** `{gmail.get('messages_file', 'N/A')}`

---

## 🚜 Layer 2: Data Processing & Structuring
Cleaned, filtered, and unified the raw data for analysis.

### 🧼 Cleaning & Noise Reduction
- **Duplicates/Holidays Removed:** {results.get('preprocessing', {}).get('removed_count', 'See Logs')}
- **Automated Noise Filtered:** {filter_res.get('gmail_noise_count', 'Checked')} emails flagged as bots/newsletters.
- **Remaining Signal:** {filter_res.get('gmail_signal_count', 'Checked')} high-value work emails.

### 🏷️ Activity Categorization
The system identified the following professional activity distribution:
{results.get('cat_distribution_md', '- *No distribution data available*')}

### 🔗 Contextual Linking
- **Connected Work Items:** {link.get('link_count', 0)} links found between emails and meetings.
- **Master File:** `{results.get('final_file_name', 'N/A')}`

---

## ✅ Status: READY FOR AI ANALYSIS
The data has been fully structured and is now in the `One Common Format`. You can proceed to the Intelligence Layer to generate insights.

---
*Generated by AI-Powered Personal Analytics Agent v1.0*
"""

    with open(report_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    
    print(f"{Fore.GREEN}[REPORT] Execution summary saved -> {report_path.name}")
    return report_path
